### ISSUE TITLE
Change research url to resources

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Religion#2]
We changed the research page to resources and the url is still reading research. Just need it to say resources.

**Comment by tu-chill** [comment]
Aye. I'll look at the nav data file. But this might be stuck in cache or maybe travis is failing to build. I'll look at it tonight.

C.Hill@Temple.edu<mailto:C.Hill@Temple.edu>
Director, Marketing Technology
Temple Liberal Arts
215.360.1895

On Sep 7, 2017, at 4:59 PM, Camille Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #2<https://github.com/TULiberalArts/Religion/issues/2> to @tu-chill<https://github.com/tu-chill>.

**Comment by CVE82** [comment]
Stop answering Issues and Emails!!!! =D It was my fault I forgot to swap out the permalink we are all good and I’ll close the issue…

Camille V. Elliott
Coordinator, Project Manager
Marketing and Communications
College of Liberal Arts
Temple University

837 Anderson Hall
1114 W. Berks St.
Philadelphia, PA 19122
(215) 204-6210
tuf77787@temple.edu<mailto:tuf77787@temple.edu>
cla.temple.edu<http://www.cla.temple.edu/>
